# -*- coding: utf-8 -*-
"""Arboles de Decisión

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zDrMzFk0rPVNDmF4Eef5qak3K6gbx3IZ

**Caso de Estudio:**
Una entidad financiera (FINTECH) quiere implemntar un sistema de modelo de arboles de decisión para mejorar la preaprobación de creditos de consumo por sus solicitantes de este tipo de créditos. Para este proceso vamos a utilizar las variables:

* **Edad:** Indica el numero de años que posee una persona o el tiempo que lleva en el sistema financiero.
* **Ingresos:** Engloba todos los ingresos que recibe una persona además de su salario (si lo posee).
* **Egresos:** Engloba todos los gastos y egresos del usuario en la presente entidad financiera.
* **Monto (EAD):**

El ejercicio se llevo a cabo en USD

0. Se procede con la carga de las librerias de trabajo
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

"""1. Se procede con la carga de los datos de trabajo"""

nxl='/content/2. HeartDisease (1).xlsx'
XDB=pd.read_excel(nxl,sheet_name=1)
XD=XDB.iloc[:,[1,10,11,25]] #Variables de entrada
yd=XDB.iloc[:,32] #Variable de salida

"""2. Se implementa el modelo del arboles"""

mar=DecisionTreeClassifier(criterion='gini',max_depth=4)
mar.fit(XD, yd) #El modelo busca la relación entrada/salida
ydp=mar.predict(XD) #Esto es lo que pronostica el modelo

#Se construye la matriz de confusión
cm=confusion_matrix(yd, ydp)
display(cm)
VN=cm[0,0];FP=cm[0,1];FN=cm[1,0];VP=cm[1,1]
#metricas de desempeño
exactitud=((VP+VN)/(VP+VN+FP+FN))*100
print("La exactitud es:",exactitud)
sensibilidad=(VP/(VP+FN))*100
print("La sensibilidad es:",sensibilidad)
especificidad=(VN/(VN+FP))*100
print("La especificidad es:",especificidad)
precisión=(VP/(VP+FP))*100
print("La precisión es:",precisión)

"""**3. Despliegue del arbol de decisión**"""

from sklearn.tree import export_graphviz #Exporta los datos a un grafico
from pydotplus import graph_from_dot_data #Garaficador
vs=["Edad", "Ingresos", "Egresos", "Monto"] #Título del árbol
dot_data=export_graphviz(mar,feature_names=vs) #Exportar graficco PDF
graph=graph_from_dot_data(dot_data) # Hacemos el Graficado
graph.write_png("arbol.png")

#Por la Izquierda viajan los positivo y por la derecha los negativos

"""**Analisis de Reusltados:**
De la base de datos se puede observar un total de 2959 solicitantes de crédito que poseen la categoría
de prenegados, mientras que para la categoría de preaprobados la matriz cuenta con un total de 2883 créditos preaprobados. De los 2959 datos, el modelo pronóstico correctamente un total de 2301 datos. De los 2883 preaprobados el modelo pronóstico correctamente un total de 2239. El modelo logra identificar en un 77% los créditos prenegados(2301/
2959), mientras que el modelo logró identificar en un 77.66% los créditos preprobados (2239/2883).

Al estar por encima del 75%, el modelo tiene un muy buen desempeño general. Con respecto a las métricas podemos observar que el modelo logró Exactitud, 77.71%, lo que indica el buen comportamiento general del modelo frente a la clasificación de créditos en las dos categorías de preaprobación. Se destacan la espcificidad y la precisión las cuales lograron valores en promedio por encima del 77%, lo que supera el limite inferior definido para este tipo de modelos de clasificación el cual se ubica en el 75%.

De acuerdo con el árbol de decisión se destaca un
porcentaje de aprobaciór
<=322 and Ing<=376 and N
nodo puro (10/0) el cual posee la siguiente regla de decisión, Si una persona cumple con esta
SI Monto<=322 and Ing>376 and Egre<=685 and Ing>644, tendrá una probabilidad de aprobación del 100%. Es importante destacar que los nodos puros poseen un gini=0 (El modelo diferencia muy bien los buenapagas).

A pesar de la no existencia de más nodos puros, se detacan los nodos extremos o las reglas del negocio extremas. Se destaca una segunda regla que lograr un porcentaje de aprobación 99%, y la cual posee la siguiente estructura: Si Monto <=322 and Ing<=376 and Monto<=178 and Ing<=232. Por su parte, el nodo derecho posee un porcentaje de negación del 98%, en donde la regla se define: Si Monto>322 and Ing.›896 and Monto>961 and Ing>1178 (7/576).
"""

nxl ='/content/2. HeartDisease (1).xlsx'
XDB1nuevo = pd.read_excel(nxl, sheet_name=1)
XDnuevo = XDB1nuevo.iloc[:, [1, 2, 3, 4]] # Variables de entrada para nuevos pacientes
ydpnuevo = mar.predict(XDnuevo)
display(ydpnuevo)
XDnuevo['Prediction'] = ydpnuevo
display(XDnuevo)