# -*- coding: utf-8 -*-
"""Final AN Clusterizacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yx5tDGLMZ_M0LTWsh7UTZ59kIocaD7Yt

##Caso de estudio

El análisis estará enfocado en segmentar consumidores según sus hábitos de compra y comportamiento dentro de la plataforma de comercio. La empresa busca identificar grupos de clientes con características similares relacionadas con frecuencia de compra, nivel de gasto y comportamiento de consumo.


La segmentación obtenida permitirá diseñar estrategias comerciales más personalizadas para cada perfil de consumidor, optimizando campañas de marketing, promociones y programas de fidelización. Además, este análisis facilitará una mejor comprensión del comportamiento de los clientes y apoyará la toma de decisiones basada en datos.

**Variables de entrada**

Frequency of Purchases: Frecuencia con la que el cliente realiza compras en la plataforma. Permite analizar hábitos de consumo y niveles de recurrencia.

Previous Purchases: Cantidad de compras previas realizadas por el consumidor. Ayuda a evaluar el historial de interacción y experiencia del cliente con la empresa.

Purchase Amount (USD): Monto de dinero gastado por el consumidor. Permite identificar si un mayor nivel de gasto se relaciona con una mayor fidelización.

Review Rating: Calificación otorgada por el cliente sobre su experiencia de compra o productos adquiridos. Refleja el nivel de satisfacción del consumidor.

Payment Method: Método de pago utilizado por el cliente. Ayuda a identificar patrones de consumo y preferencias de compra.

**Variable de salida**

Subscription Status: Indica si el consumidor posee o no una suscripción dentro de la plataforma. Esta es la variable objetivo del modelo, ya que permite clasificar a los clientes según su nivel de fidelización y compromiso con la empresa.

0. Se procede con la carga de las librerias de trabajo
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns #herramienta para graficas estadisticas

from sklearn.cluster import KMeans #herramienta de clustering

"""1. Se cargan los datos de trabajo"""

nxl='/content/sample_data/shopping_trends_updated.csv'
XDB=pd.read_csv(nxl)
XD=XDB.iloc[:,[5,10,15,16,17]] #Variables de entrada
yd=XDB.iloc[:,11] #Variable de salida

#determinar la correlacióne entre las variables
# Select only numerical columns for correlation calculation
XDB2 = XDB.iloc[:,[5,10,11,15]].copy() # Columns: Purchase Amount (USD), Review Rating, Subscription Status, Previous Purchases

# Convert 'Subscription Status' to numerical (1 for 'Yes', 0 for 'No')
XDB2['Subscription Status'] = XDB2['Subscription Status'].map({'Yes': 1, 'No': 0})

sns.heatmap(XDB2.corr(),annot=True)

"""2. Se procede con la implementación del modelo"""

np.random.seed(42) #Mismas semillas para todos
NC=5 #Habiamos dicho 5 segmentos/perfiles de clientes

# Prepare XD for KMeans: One-hot encode categorical features
# XD contains columns 5, 10, 15, 16, 17 from XDB
# Columns 16 ('Payment Method') and 17 ('Frequency of Purchases') are categorical
XD_to_encode = XDB.iloc[:,[5,10,15,16,17]].copy() # Ensure we're working on a copy
XD_to_encode.columns = ['Purchase Amount (USD)', 'Review Rating', 'Previous Purchases', 'Payment Method', 'Frequency of Purchases']

categorical_features = ['Payment Method', 'Frequency of Purchases']
XD_final = pd.get_dummies(XD_to_encode, columns=categorical_features, drop_first=False)

mkm=KMeans(n_clusters=NC,random_state=42, n_init='auto') # Added n_init='auto' to suppress future warning
# Fit KMeans model on the prepared numerical features (XD_final)
# Note: KMeans is an unsupervised algorithm, so 'y' (target variable) is not used in fit().
mkm.fit(XD_final)

#Obtenemos la caracterisizacion de cada grupo
#Representamos los perfiles de las personas mkm.cluster_centers_ que encontró el modelo
Tabla=pd.DataFrame(mkm.cluster_centers_,columns=XD_final.columns)
display(Tabla)

#para saber los porcentajes de PreApr o PreNeG por segmento, sucursal o perfil
ydp=mkm.labels_ #Me indica enq eu cluster queda clasificado cada dato
NDc=np.bincount(ydp) #Numero de datos por segmento
print("El numero de datos por cluster es:",NDc)

"""3. Porcentajes de Inscripcion"""

XDB2['cluster']=ydp
display(XDB2)

#Determinar el número de Subscribed (1) y Not Subscribed (0) por cluster
# The column representing subscription status is 'Subscription Status'
Napr = XDB2.groupby('cluster')['Subscription Status'].apply(lambda x: (x == 1).sum()).rename('Si')
Nprn = XDB2.groupby('cluster')['Subscription Status'].apply(lambda x: (x == 0).sum()).rename('No')

# Combine these into a DataFrame
df_counts = pd.concat([Napr, Nprn], axis=1)
display(df_counts)

# Calculate percentages
df_counts['Perc Si'] = df_counts['Si'] / (df_counts['Si'] + df_counts['No'])
df_counts['Perc No'] = df_counts['No'] / (df_counts['Si'] + df_counts['No'])

# Assign the final result to df2 as per original intent
df2 = df_counts
display(df2)

"""**Analisis de resultados:**


El modelo de K-Means Clustering permitió segmentar los consumidores en cinco grupos diferentes según sus hábitos de compra y comportamiento dentro de la plataforma. Los resultados muestran que existen diferencias importantes entre los perfiles de clientes, especialmente en variables relacionadas con el monto de compra, la frecuencia de compra y el número de compras previas realizadas. Además, la distribución de datos entre los clusters fue relativamente equilibrada, lo que permitió identificar segmentos de consumidores con características diferenciadas y representativas dentro de la base de datos.

A partir de la segmentación obtenida, fue posible identificar perfiles de consumidores con mayores niveles de fidelización y otros con comportamientos más ocasionales. Algunos grupos presentaron una mayor proporción de consumidores suscritos, lo que sugiere patrones de compra más constantes y un mayor compromiso con la plataforma. Estos hallazgos permiten a la empresa diseñar estrategias comerciales y campañas de marketing más personalizadas según las características y necesidades de cada segmento identificado.
"""